import type { NextPage } from 'next'
import Head from 'next/head'

import Section from '../components/home/section'

const Home: NextPage = () => {
  return (
    <div className="container mx-auto min-h-full">
  
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Section />

    </div>
  )
}

export default Home
